-- Gerenciamento de Tabelas...
-- ALTER, DROP, RENAME...

-- ALTER Table NomeTabela...
-- ADD / ALTER / DROP Objetos...

-- Adicionar uma nova coluna a uma tabela existente...
alter table Livro
add Edição smallint;

-- Alterar o tipo de dados de uma coluna...
alter table Livro
alter column Edição tinyint;

-- Adicionar chave primária...
alter table Livro
add primary key (ISBN13);

-- Excluir uma constraint de uma coluna...
alter table NomeTabela
drop constraint NomeConstraint;

-- Verificar nomes das constraints...
sp_help Livro;

-- Excluir uma coluna de uma tabela...
alter table Livro
drop column Edição;

-- Excluir uma tabela:  drop table...
drop table NomeTabela;

-- Renomear uma tabela: sp_rename...
-- sp_rename 'nome atual', 'novo nome'...
sp_rename 'Livro', 'tbl_livros';